
// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAewVhbSDMdr83YYhuHHfx0fsD7karrrLE',
    appId: '1:207745791533:web:d8c5j3m4n2p1', // This is a placeholder, web setup may be needed
    messagingSenderId: '207745791533',
    projectId: 'myapp-da297',
    authDomain: 'myapp-da297.firebaseapp.com',
    storageBucket: 'myapp-da297.appspot.com',
    databaseURL: 'https://myapp-da297-default-rtdb.asia-southeast1.firebasedatabase.app/',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAewVhbSDMdr83YYhuHHfx0fsD7karrrLE',
    appId: '1:207745791533:android:62d6f9ad967b3ec63b6aa4',
    messagingSenderId: '207745791533',
    projectId: 'myapp-da297',
    storageBucket: 'myapp-da297.appspot.com',
    databaseURL: 'https://myapp-da297-default-rtdb.asia-southeast1.firebasedatabase.app/',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAewVhbSDMdr83YYhuHHfx0fsD7karrrLE',
    appId: '1:207745791533:ios:some_ios_id', // This is a placeholder, iOS setup may be needed
    messagingSenderId: '207745791533',
    projectId: 'myapp-da297',
    storageBucket: 'myapp-da297.appspot.com',
    iosBundleId: 'com.app',
    databaseURL: 'https://myapp-da297-default-rtdb.asia-southeast1.firebasedatabase.app/',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAewVhbSDMdr83YYhuHHfx0fsD7karrrLE',
    appId: '1:207745791533:ios:some_macos_id', // This is a placeholder, macOS setup may be needed
    messagingSenderId: '207745791533',
    projectId: 'myapp-da297',
    storageBucket: 'myapp-da297.appspot.com',
    iosBundleId: 'com.app',
    databaseURL: 'https://myapp-da297-default-rtdb.asia-southeast1.firebasedatabase.app/',
  );
}
